Modules:
  Levitation: 5
  Prefix: "&b[Superfly]"

Superfly:
  Enabled:
    Active: true
    Title: "&b&lSuperfly"
    Subtitle: "&fFlight mode &aEnabled"
    Sound: LEVEL_UP:10:2
  Disabled:
    Active: true
    Title: "&b&lSuperfly"
    Subtitle: "&fFlight mode &cDisabled"
  Permission:
    Active: true
    Title: "&b&lSuperfly"
    Subtitle: "&cYou don't have permissions"
    Sound: LAVA_POP:10:2

Message:
  Enabled: "%prefix% &fYour flight mode has been &aActivated"
  Disabled: "%prefix% &fYour flight mode has been &cDisabled"
  Error: "%prefix% &cThe command you just executed does not exist"
  Reload: "%prefix% &aThe plugin folders were successfully reloaded"
  NoPermission: "%prefix% &cYou do not have permissions to run this command"
  Permission: "%prefix% &fYou need rank &e[Sxmuray] &fto get flight mode, you can purchase it at &astore.aquatic.studios"