main: aquatic.sxmuray.superfly.Main
name: Superfly
version: 2.0.1
author: Sxmuray
description: Aquatic Studios - Public use plugin (Flight Mode)
website: https://www.spigotmc.org/members/sxmuray.1339322/

commands:
  fly:
    description: Command to run flight mode
  superfly:
    description: Use command for flight mode
    aliases:
      - sfly